export const ANDROID_VERSIONS: any = {
    // "14": "Upside Down Cake",
    // "13": "Tiramisu",
    // "12L": "Snow Cone v2",
    // "12": "Snow Cone",
    // "11": "Red Velvet Cake",
    // "10": "Quince Tart",
    "9": "Pie",
    "8.1": "Oreo (MR1)",
    "8.0": "Oreo",
    "7.1": "Nougat (MR1)",
    "7.0": "Nougat",
    "6.0": "Marshmallow",
    "5.1": "Lollipop (MR1)",
    "5.0": "Lollipop",
    "4.4": "KitKat",
    "4.3": "Jelly Bean (MR2)",
    "4.2": "Jelly Bean (MR1)",
    "4.1": "Jelly Bean",
    "4.0": "Ice Cream Sandwich",
    "3.2": "Honeycomb (MR2)",
    "3.1": "Honeycomb (MR1)",
    "3.0": "Honeycomb",
    "2.3": "Gingerbread",
    "2.2": "Froyo",
    "2.1": "Eclair",
    "2.0": "Eclair",
    "1.6": "Donut",
    "1.5": "Cupcake",
    "1.1": "Petit Four",
    "1.0": "Alpha"
};
